# Generated by Django 4.0.6 on 2022-07-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='karma',
            field=models.CharField(default='Не опубликован', max_length=20, verbose_name='Карма'),
        ),
    ]
