# Generated by Django 4.0.6 on 2022-07-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='karma',
            field=models.CharField(default='Не хорошая', max_length=20, verbose_name='Карма'),
        ),
    ]
