# Generated by Django 4.0.6 on 2022-07-19 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='posts_total',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
